name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.17.0
      uses: actions/setup-node@v2
      with:
        node-version: 16.17.0
    - run: npm install
    - run: npm audit fix
    - run: npm ci
    - run: npm run build --if-present
    - run: npm install eslint
    - run: npx eslint . --fix
    - run: npm test
